---
namespace: ansi_colle
name: windows
version: 1.0.0

readme: README.md

authors:
  - Chun Pan Yung

description: Configure Windows and WSL

license:
  - MIT

tags:
  - windows

dependencies:
  "ansi_colle.mods": "*"
  "community.general": "*"
  "community.windows": "*"

repository: http://github.com/ChunPanYung/ansi_colle-windows

build_ignore: []
