---
namespace: ansi_colle
name: windows
version: 1.0.0

readme: README.md

authors:
  - Chun Pan Yung

description: Configure Windows and WSL

license:
  - MIT

tags:
  - windows

dependencies:
  "ansible.windows": "*"
  "community.general": "*"
  "community.windows": "*"

repository: http://example.com/repository

build_ignore: []
