---
- name: Configure Windows
  hosts: windows
  tasks:
    - name: Ping test
      tags: ping
      ansible.windows.win_ping:

    - name: Check my user name
      ansible.windows.win_whoami:

    - name: Check my sudo user name
      ansible.windows.win_whoami:
      become: true

    - name: Check ansible facts
      ansible.builtin.debug:
        var: ansible_facts
